### PR TITLE
Unquote warning

### PR DESCRIPTION
**Pull request by quackduck**
You probably don't want the warning to be quoted.

### CODE REVIEW

**Comment by khrj** [comment]
Why though?

**Comment by quackduck** [comment]
To be sure people know it's you saying the warning.

**Comment by quackduck** [comment]
Btw, does this run the JS on the calling machine or a server?

**Comment by quackduck** [comment]
In the first case, users should already know the risks of running any JS. In the second, that's your issue and you should be handling it.

In both cases, the warning is unnecessary.

**Comment by quackduck** [comment]
Just a suggestion: you should probably add more info about how to use this, what exactly it does and examples.

**Comment by khrj** [comment]
> Btw, does this run the JS on the calling machine or a server?

Server, its not possible to execute JS, that would be a huge security risk

> In the first case, users should already know the risks of running any JS.

Even if this was possible, they've literally given no consent to this, so they wouldn't know any risks...

>  In the second, that's your issue and you should be handling it.

The warning is for people wanting to self-host the bot, in which case its _their issue_

Closing because the quote looks fine to me 🤷

**Comment by quackduck** [comment]
> The warning is for people wanting to self-host the bot, in which case its their issue

You should probably make that clearer on the readme

**Pull request closed without merging**
